version: '3.8'
services:
  arangodb:
    image: arangodb/arangodb:latest
    container_name: arangodb
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=xN7G9FEbmG*CRAvqhh.vM
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    restart: unless-stopped

volumes:
  arangodb_data:
  arangodb_apps: